// src/components/Game/GameScore.svelte
<script setup lang="ts">
  import { scale } from 'svelte/transition'
  import { NUMBER_FORMATTER } from '~/lib/utils'
  import GameManager from '~/models/GameManager'

  export let game: GameManager
  const gameState = game.state

  let prevScore = 0
  let scoreDiff = 0
  $: {
    const score = $gameState.score
    if (prevScore !== 0 && score > prevScore) {
      scoreDiff = score - prevScore
    }
    prevScore = score
  }
</script>

<div class="flex gap-2">
  <div class="score-container">
    <span>SCORE</span>
    <div class="relative">
      {#key $gameState.score}
        <!-- content here -->
        <div in:scale={{ duration: 100, opacity: 0.5 }}>
          {NUMBER_FORMATTER.format($gameState.score)}
        </div>
      {/key}

      {#if scoreDiff !== 0}
        {@const rand = Math.random()}
        <span
          class="additional-score absolute text-grid-bg text-2xl left-1/2 bottom-1/2"
          on:animationend={() => (scoreDiff = 0)}
          style="
            --end-x: {50 + (rand < 0.5 ? 1 : -1) * 50 * (rand + 1)}%;
            --end-y: {300 + rand * 50}%;
          "
        >
          +{scoreDiff}
        </span>
      {/if}
    </div>
  </div>
  <!-- Best Score -->
  <div class="score-container">
    <span class="">BEST</span>
    <span>{$gameState.bestScore}</span>
  </div>
</div>

<style>
  .score-container {
    @apply w-16 px-2 py-1 bg-[#454545] rounded text-white text-sm font-bold text-center;
    @apply flex flex-col;
  }

  .additional-score {
    animation: additionalScoreFade 500ms ease-in-out;
  }

  @keyframes additionalScoreFade {
    100% {
      opacity: 0.2;
      scale: 0.8;
      left: var(--end-x);
      bottom: var(--end-y);
    }
  }
</style>

// src/components/GameScore.tsx
import type { Accessor } from "solid-js"
import { useValueDifference } from "~/hooks/useValueDiff"
import clsx from "~/lib/clsx"

const nbrFormat = new Intl.NumberFormat(undefined)

interface Props {
  score: Accessor<number>
  bestScore: Accessor<number>
}
const scoreBtnClass = clsx(
  "flex flex-col gap-1",
  "relative w-[5.2rem] h-[2.8rem]",
  "rounded bg-[#454545] font-bold text-sm",
  "items-center justify-center",
)
export default function GameScoreWithBestScore({ score, bestScore }: Props) {
  const [bestScoreDiff, setBestScoreDiff] = useValueDifference(bestScore)
  return (
    <div class="flex gap-1">
      <GameScore score={score} />
      <div class={scoreBtnClass}>
        <span class="text-xs">TOP SCORE</span>
        <div
          style={{
            animation: bestScoreDiff() !== 0 ? "pop 200ms ease-in-out" : "none",
          }}
          onanimationend={() => {
            setBestScoreDiff(0)
          }}
        >
          {nbrFormat.format(bestScore())}
        </div>
      </div>
    </div>
  )
}

export function GameScore({ score }: { score: Accessor<number> }) {
  const [scoreDiff, setScoreDiff] = useValueDifference(score)

  return (
    <div class={scoreBtnClass}>
      <span class="text-xs">SCORE</span>
      <div
        style={{
          animation: scoreDiff() !== 0 ? "pop 200ms ease-in-out" : "none",
        }}
      >
        {nbrFormat.format(score())}
      </div>

      <div
        class="absolute text-2xl"
        style={{
          opacity: scoreDiff() > 0 ? 1 : 0,
          animation: scoreDiff() > 0 ? "zoomAndFade 500ms ease-in-out" : "none",
        }}
        onanimationend={() => {
          setScoreDiff(0)
        }}
      >
        +{scoreDiff()}
      </div>
    </div>
  )
}
