// src/components/Game/Tile.svelte
<script lang="ts">
  import { scale } from 'svelte/transition'
  import Tile from '~/models/Tile'
  import { COLORS } from '~/lib/consts'

  export let tile: Tile

  const x = tile._x
  const y = tile._y
  const _value = tile._value
  const scaleVal = tile.scale

  $: value = $_value
</script>

<div
  class="cell tile absolute flex justify-center items-center font-bold"
  style="--x: {$x}; --y: {$y}; scale: {$scaleVal};"
  style:background-color={COLORS.get(value)?.bg ?? ''}
  in:scale={{ duration: 200, opacity: 0.5 }}
>
  <span style:color={COLORS.get(value)?.fg ?? ''}>{value}</span>
</div>

<style>
  .tile {
    top: calc(
      var(--grid-padding) + var(--y) * (var(--cell-size) + var(--grid-gap))
    );
    left: calc(
      var(--grid-padding) + var(--x) * (var(--cell-size) + var(--grid-gap))
    );
  }
</style>

// src/components/Tile.tsx
import { createEffect, createSignal } from "solid-js"
import { COLORS, CSS_POS_CALC } from "~/lib/consts"
import type { TileType } from "~/lib/types"

interface Props {
  tile: TileType
  theme?: string
}

export default function TileComponent({ tile }: Props) {
  const [popAnimation, setPopAnimation] = createSignal("")

  createEffect(() => {
    tile.value
    setPopAnimation("pop")
  })

  return (
    <div
      class="tile absolute font-bold"
      id={tile.id}
      style={{
        left: CSS_POS_CALC(tile.x),
        top: CSS_POS_CALC(tile.y),
        "background-color": COLORS.get(tile.value)?.bg,
        animation: popAnimation() ? "pop 200ms ease-in-out" : "none",
      }}
      onAnimationEnd={() => setPopAnimation("")}
    >
      <span
        style={{
          color: COLORS.get(tile.value)?.fg ?? "",
        }}
      >
        {tile.value}
      </span>
    </div>
  )
}
